version: '3'

volumes:
  postgres_data: {}

services:
  web:
    build: client/
    environment:
      - REACT_APP_API_URL=http://localhost:${API_PORT}/graphql
    ports:
      - '80:80'
    links:
      - api
  api:
    build:
      context: ./server
    environment:
      - BATCH_SIZE=${BATCH_SIZE}
      - PORT=${API_PORT}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./models:/models
    depends_on:
      - db
  scraper:
    build: ./scraper
    depends_on:
      - db
    volumes:
      - ./models:/models
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
