version: '3.5'

volumes:
  postgres_data: {}

services:
  web:
    build:
      context: client/
      args:
        REACT_APP_API_UR: 'http://localhost:${API_PORT}/graphql'
    ports:
      - '80:80'
    links:
      - api
  api:
    build:
      context: ./server
    environment:
      - PORT=${API_PORT}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./db:/db
    depends_on:
      - db
  scraper:
    build: ./scraper
    environment:
      - BATCH_SIZE=${BATCH_SIZE}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - SCRAPE_SCHEDULE=${SCRAPE_SCHEDULE}
    depends_on:
      - db
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - ./db:/db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
